// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MyApp.UITest.UIMaps.MyLittleImprovedUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class MyLittleImprovedUIMap
    {
        
        #region Properties
        public UIMyAppCounterWindow UIMyAppCounterWindow
        {
            get
            {
                if ((this.mUIMyAppCounterWindow == null))
                {
                    this.mUIMyAppCounterWindow = new UIMyAppCounterWindow();
                }
                return this.mUIMyAppCounterWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMyAppCounterWindow mUIMyAppCounterWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMyAppCounterWindow : WpfWindow
    {
        
        public UIMyAppCounterWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyApp - Counter";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyApp - Counter");
            #endregion
        }
        
        #region Properties
        public UITabControl UITabControl
        {
            get
            {
                if ((this.mUITabControl == null))
                {
                    this.mUITabControl = new UITabControl(this);
                }
                return this.mUITabControl;
            }
        }
        #endregion
        
        #region Fields
        private UITabControl mUITabControl;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITabControl : WpfTabList
    {
        
        public UITabControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabList.PropertyNames.AutomationId] = "MyApp.MainWindow.TabControl";
            this.WindowTitles.Add("MyApp - Counter");
            #endregion
        }
        
        #region Properties
        public UITabItem1 UITabItem1
        {
            get
            {
                if ((this.mUITabItem1 == null))
                {
                    this.mUITabItem1 = new UITabItem1(this);
                }
                return this.mUITabItem1;
            }
        }
        #endregion
        
        #region Fields
        private UITabItem1 mUITabItem1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITabItem1 : WpfTabPage
    {
        
        public UITabItem1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.AutomationId] = "MyApp.MainWindow.TabItem1";
            this.WindowTitles.Add("MyApp - Counter");
            #endregion
        }
        
        #region Properties
        public WpfButton UIIncreaseButton
        {
            get
            {
                if ((this.mUIIncreaseButton == null))
                {
                    this.mUIIncreaseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIIncreaseButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "MyApp.MainWindow.IncreaseButton";
                    this.mUIIncreaseButton.WindowTitles.Add("MyApp - Counter");
                    #endregion
                }
                return this.mUIIncreaseButton;
            }
        }
        
        public UICounterLabel UICounterLabel
        {
            get
            {
                if ((this.mUICounterLabel == null))
                {
                    this.mUICounterLabel = new UICounterLabel(this);
                }
                return this.mUICounterLabel;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIIncreaseButton;
        
        private UICounterLabel mUICounterLabel;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICounterLabel : WpfText
    {
        
        public UICounterLabel(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.AutomationId] = "MyApp.MainWindow.CounterLabel";
            this.WindowTitles.Add("MyApp - Counter");
            #endregion
        }
        
        #region Properties
        public WpfText UICounterText
        {
            get
            {
                if ((this.mUICounterText == null))
                {
                    this.mUICounterText = new WpfText(this);
                    #region Search Criteria
                    this.mUICounterText.SearchProperties[WpfText.PropertyNames.Name] = "0";
                    this.mUICounterText.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUICounterText.WindowTitles.Add("MyApp - Counter");
                    #endregion
                }
                return this.mUICounterText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUICounterText;
        #endregion
    }
}
